name: Android CI

on:
  # TODO switch back to push to branch trigger when ecverything works
  # push:
    # branches: [ "release" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # set up environment
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    # unlock repository secrets with git-crypt
    - uses: actions/checkout@master
    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    # run gradle scripts
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Bump minor version number
      run: ./gradlew bumpMinorVersion
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to Play Store
      run: ./gradlew publishReleaseBundle
