name: Android CI

on:
  # TODO switch back to push to branch trigger when ecverything works
  # push:
  # branches: [ "release" ]
  workflow_dispatch:

env:
  STORE_PATH: './store_key'

jobs:
  bump_version_and_publish:
    runs-on: ubuntu-latest

    steps:
      # set up gradle
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # unlock repository secrets with git-crypt
      - uses: actions/checkout@master
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      # write store file location to local props
      - name: Create local.properties
        run: |
          touch local.porperties
          echo 'RELEASE_STORE_FILE=${{ github.workspace }}/store_key.jks' >> local.properties
      # create keystore file and write keystore secret data
      # touch ${{ github.workspace }}/store_key
      # run: |
      #          echo `${{ secrets.RELEASE_STORE }} | base64 --decode` >> ${{ github.workspace }}/store_key
      - name: Write keystore data from secrets
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileDir: ${{ github.workspace }}
          fileName: store_key.jks
          encodedString: ${{ secrets.RELEASE_STORE }}

      - name: Ensure keystore
        run: cat ${{ github.workspace }}/store_key.jks

      # run gradle scripts
      - name: Bump minor version number
        run: ./gradlew bumpMinorVersion
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to Play Store
        run: ./gradlew publishReleaseBundle
